"""Logical backup of the configured database.

A stand-in for ``pg_dump``, which is not installed on this machine. Writes
``CREATE TABLE`` / ``CREATE INDEX`` / ``INSERT`` statements so the whole schema
and every row can be restored by running the file against PostgreSQL.

Run with::

    python -m backups.dump_sql
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import Index, MetaData, Table, inspect, select
from sqlalchemy.schema import CreateIndex, CreateTable
from sqlalchemy.dialects import postgresql

OUT_DIR = Path(__file__).resolve().parent


def _quote(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (bytes, bytearray, memoryview)):
        return "'" + bytes(value).hex() + "'::bytea"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def main() -> int:
    from app.database import engine

    dialect = postgresql.dialect()
    inspector = inspect(engine)
    tables = sorted(inspector.get_table_names())
    # ``alembic_version`` is bookkeeping, but it is restored too: without it a
    # restore would look like an unversioned database.
    meta = MetaData()

    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    out = OUT_DIR / f"pre_reconciliation_{stamp}.sql"

    with engine.connect() as connection:
        lines: list[str] = [
            "-- Logical backup generated by backups/dump_sql.py",
            f"-- source: {engine.url.render_as_string(hide_password=True)}",
            f"-- at:     {datetime.now(timezone.utc).isoformat()}",
            "--",
            "BEGIN;",
            "",
        ]

        for name in tables:
            table = Table(name, meta, autoload_with=engine)
            lines.append(str(CreateTable(table).compile(dialect=dialect)).rstrip() + ";")
            lines.append("")

            for index in inspector.get_indexes(name):
                columns = index.get("column_names") or []
                # Partial indexes carry None entries for expression columns,
                # which cannot be rebuilt faithfully from reflection.
                if not index.get("name") or any(c is None for c in columns):
                    lines.append(
                        f"-- skipped index {index.get('name')} "
                        "(partial or expression index; recreate manually)"
                    )
                    continue
                try:
                    built = Index(
                        index["name"],
                        *(table.c[c] for c in columns),
                        unique=index.get("unique", False),
                    )
                    lines.append(
                        str(CreateIndex(built).compile(dialect=dialect)).rstrip() + ";"
                    )
                except Exception as exc:  # pragma: no cover - defensive
                    lines.append(f"-- skipped index {index['name']}: {exc}")
            lines.append("")

            rows = connection.execute(select(table)).mappings().all()
            if not rows:
                lines.append(f"-- {name}: 0 rows")
                lines.append("")
                continue

            columns = list(rows[0].keys())
            col_sql = ", ".join(f'"{c}"' for c in columns)
            for row in rows:
                values = ", ".join(_quote(row[c]) for c in columns)
                lines.append(f'INSERT INTO "{name}" ({col_sql}) VALUES ({values});')
            lines.append(f"-- {name}: {len(rows)} rows")
            lines.append("")

        lines.append("COMMIT;")
        out.write_text("\n".join(lines), encoding="utf-8")

    size = out.stat().st_size
    print(f"backup written: {out} ({size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
