import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { api } from "@/lib/api";

type Resource = { id: number; title: string; category: string; language: string; description?: string; is_approved?: boolean; is_published?: boolean };

export default function AdminResources() {
  const [items, setItems] = useState<Resource[]>([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<Resource | null>(null);

  useEffect(() => { void load(); }, []);
  async function load() { try { setLoading(true); const [published, pending] = await Promise.all([api.get<Resource[]>("/api/choir/"), api.get<Resource[]>("/api/admin/pending-resources")]); const merged = [...(published.data || []), ...(pending.data || [])]; setItems(Array.from(new Map(merged.map((item) => [item.id, item])).values())); } catch (error: any) { Alert.alert("Resources unavailable", error?.response?.data?.detail || "Unable to load resources."); } finally { setLoading(false); } }
  async function moderate(id: number, action: "approve" | "reject" | "delete") { try { if (action === "approve") await api.put(`/api/admin/approve-resource/${id}`); else await api.delete(`/api/admin/resources/${id}`); await load(); } catch (error: any) { Alert.alert("Action failed", error?.response?.data?.detail || "Unable to update this resource."); } }
  async function saveEdit() { if (!editing) return; try { const form = new FormData(); form.append("title", editing.title); form.append("category", editing.category); form.append("language", editing.language); form.append("description", editing.description || ""); await api.put(`/api/choir/${editing.id}`, form); setEditing(null); await load(); } catch (error: any) { Alert.alert("Save failed", error?.response?.data?.detail || "Unable to edit this resource."); } }
  if (loading) return <View style={styles.center}><ActivityIndicator color="#0B6623" /></View>;
  if (editing) return <View style={styles.container}><Text style={styles.title}>Edit Resource</Text><TextInput style={styles.input} value={editing.title} onChangeText={(value) => setEditing({ ...editing, title: value })} /><TextInput style={styles.input} value={editing.category} onChangeText={(value) => setEditing({ ...editing, category: value })} /><TextInput style={styles.input} value={editing.language} onChangeText={(value) => setEditing({ ...editing, language: value })} /><TextInput style={styles.area} multiline value={editing.description || ""} onChangeText={(value) => setEditing({ ...editing, description: value })} /><Pressable style={styles.button} onPress={saveEdit}><Text style={styles.buttonText}>Save Changes</Text></Pressable><Pressable onPress={() => setEditing(null)}><Text style={styles.cancel}>Cancel</Text></Pressable></View>;
  return <View style={styles.container}><Text style={styles.title}>Manage Choir Resources</Text><FlatList data={items} keyExtractor={(item) => String(item.id)} renderItem={({ item }) => <View style={styles.card}><Text style={styles.heading}>{item.title}</Text><Text style={styles.meta}>{item.category} · {item.language}</Text><Text style={styles.meta}>{item.is_approved ? "Approved" : "Pending approval"}</Text><View style={styles.actions}><Pressable onPress={() => setEditing(item)}><Text style={styles.action}>Edit</Text></Pressable>{!item.is_approved ? <Pressable onPress={() => moderate(item.id, "approve")}><Text style={styles.action}>Approve</Text></Pressable> : null}<Pressable onPress={() => moderate(item.id, item.is_approved ? "delete" : "reject")}><Text style={styles.danger}>{item.is_approved ? "Delete" : "Reject"}</Text></Pressable></View></View>} ListEmptyComponent={<Text style={styles.empty}>No resources found.</Text>} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, padding: 18, backgroundColor: "#fff" }, center: { flex: 1, justifyContent: "center", alignItems: "center" }, title: { fontSize: 28, fontWeight: "800", color: "#0B6623", marginBottom: 15 }, card: { borderWidth: 1, borderColor: "#e5e5e5", borderRadius: 12, padding: 15, marginBottom: 10 }, heading: { fontSize: 17, fontWeight: "800" }, meta: { color: "#666", marginTop: 5 }, actions: { flexDirection: "row", gap: 18, marginTop: 12 }, action: { color: "#0B6623", fontWeight: "800" }, danger: { color: "#C62828", fontWeight: "800" }, input: { borderWidth: 1, borderColor: "#ddd", borderRadius: 9, padding: 12, marginBottom: 10 }, area: { borderWidth: 1, borderColor: "#ddd", borderRadius: 9, padding: 12, minHeight: 100, marginBottom: 10, textAlignVertical: "top" }, button: { backgroundColor: "#0B6623", padding: 14, borderRadius: 9, alignItems: "center" }, buttonText: { color: "#fff", fontWeight: "800" }, cancel: { color: "#0B6623", fontWeight: "700", textAlign: "center", marginTop: 16 }, empty: { color: "#777", textAlign: "center", marginTop: 40 } });
