services:
  - type: web
    name: catholic-readings-and-choir-resource-app
    runtime: python
    plan: free

    rootDir: backend

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT

    autoDeploy: true

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5

      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        sync: false

      - key: ALGORITHM
        value: HS256

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "30"

      - key: ENVIRONMENT
        value: production

      - key: FRONTEND_URL
        value: https://catholic-readings-and-choir-resource-app.vercel.app

      - key: MPESA_ENVIRONMENT
        value: production

      - key: MPESA_CONSUMER_KEY
        sync: false

      - key: MPESA_CONSUMER_SECRET
        sync: false

      - key: MPESA_PASSKEY
        sync: false

      - key: MPESA_SHORTCODE
        sync: false

      - key: MPESA_CALLBACK_URL
        value: https://catholic-readings-and-choir-resource-app.onrender.com/api/payments/mpesa/callback

      - key: MPESA_ACCOUNT_REFERENCE
        value: CatholicReadings

      - key: MPESA_TRANSACTION_DESCRIPTION
        value: Catholic Readings Subscription

      - key: MPESA_TRANSACTION_TYPE
        value: CustomerPayBillOnline

      - key: MPESA_MONTHLY_AMOUNT
        value: "10"

      - key: MPESA_RECIPIENT_NUMBER
        value: "0748153302"